using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Microsoft.Win32;

namespace WISOptimizer.Core
{
    public static class DeploymentScriptManager
    {
        public static bool SavePowerShellScript(IEnumerable<string> commands, out string savedPath)
        {
            savedPath = string.Empty;
            var backupPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Backup");
            var profilesPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Profiles");
            var defaultDir = Directory.Exists(profilesPath) ? profilesPath : backupPath;

            if (!Directory.Exists(defaultDir))
            {
                Directory.CreateDirectory(defaultDir);
            }

            var dialog = new SaveFileDialog
            {
                Filter = "PowerShell Script (*.ps1)|*.ps1|Batch Script (*.bat)|*.bat",
                FileName = $"WIS_Deployment_{DateTime.Now:yyyyMMdd_HHmmss}.ps1",
                InitialDirectory = defaultDir,
                Title = "Save Deployment Script"
            };

            if (dialog.ShowDialog() != true)
            {
                return false;
            }

            var content = BuildScript(dialog.FileName, commands);
            File.WriteAllText(dialog.FileName, content, Encoding.UTF8);
            savedPath = dialog.FileName;
            return true;
        }

        private static string BuildScript(string fileName, IEnumerable<string> commands)
        {
            var sb = new StringBuilder();
            var isBat = Path.GetExtension(fileName).Equals(".bat", StringComparison.OrdinalIgnoreCase);
            if (isBat)
            {
                sb.AppendLine("@echo off");
                sb.AppendLine("powershell -NoProfile -ExecutionPolicy Bypass -Command \"");
                foreach (var cmd in commands)
                {
                    sb.AppendLine(cmd.Replace("\"", "\\\""));
                }
                sb.AppendLine("\"");
                return sb.ToString();
            }

            sb.AppendLine("# Generated by WISOptimizer");
            sb.AppendLine($"# {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("$ErrorActionPreference = 'Continue'");
            foreach (var cmd in commands)
            {
                sb.AppendLine(cmd);
            }
            return sb.ToString();
        }
    }
}
