using System;
using System.Text;

namespace WISOptimizer.Core
{
    public static class DeploymentScriptGenerator
    {
        public static string GenerateMasterScript(OptimizationSettings settings)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by WISOptimizer [Master Deployment Script]");
            sb.AppendLine($"# Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("$ErrorActionPreference = 'Continue'");
            sb.AppendLine();
            sb.AppendLine("Write-Host 'Starting WISOptimizer Master Deployment...' -ForegroundColor Cyan");

            // ═══ Windows Update ═══
            sb.AppendLine("\n# --- Windows Update ---");
            if (settings.DisableWindowsUpdate) {
                sb.AppendLine("Set-Service -Name wuauserv -StartupType Disabled");
                sb.AppendLine("Stop-Service -Name wuauserv -Force -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Set-Service -Name wuauserv -StartupType Manual");
            }

            if (settings.DisableDeliveryOpt) {
                sb.AppendLine("Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization' -Name 'DODownloadMode' -Value 0 -Type DWord -Force -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Remove-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization' -Name 'DODownloadMode' -Force -ErrorAction SilentlyContinue");
            }

            if (settings.DisableUpdateOrchestrator) {
                sb.AppendLine("Set-Service -Name UsoSvc -StartupType Disabled");
                sb.AppendLine("Stop-Service -Name UsoSvc -Force -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Set-Service -Name UsoSvc -StartupType Automatic");
            }

            // ═══ Taskbar Customization ═══
            sb.AppendLine("\n# --- Taskbar Customization ---");
            string advPath = "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced";
            string searchPath = "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Search";

            sb.AppendLine($"if (!(Test-Path '{advPath}')) {{ New-Item -Path '{advPath}' -Force | Out-Null }}");
            sb.AppendLine($"if (!(Test-Path '{searchPath}')) {{ New-Item -Path '{searchPath}' -Force | Out-Null }}");

            sb.AppendLine(settings.TaskbarLeft 
                ? $"Set-ItemProperty -Path '{advPath}' -Name 'TaskbarAl' -Value 0 -Force" 
                : $"Set-ItemProperty -Path '{advPath}' -Name 'TaskbarAl' -Value 1 -Force");

            sb.AppendLine(settings.HideTaskView 
                ? $"Set-ItemProperty -Path '{advPath}' -Name 'ShowTaskViewButton' -Value 0 -Force" 
                : $"Set-ItemProperty -Path '{advPath}' -Name 'ShowTaskViewButton' -Value 1 -Force");

            sb.AppendLine(settings.RemoveWidgets 
                ? $"Set-ItemProperty -Path '{advPath}' -Name 'TaskbarDa' -Value 0 -Force" 
                : $"Set-ItemProperty -Path '{advPath}' -Name 'TaskbarDa' -Value 1 -Force");

            sb.AppendLine(settings.HideSearch 
                ? $"Set-ItemProperty -Path '{searchPath}' -Name 'SearchboxTaskbarMode' -Value 0 -Force" 
                : $"Set-ItemProperty -Path '{searchPath}' -Name 'SearchboxTaskbarMode' -Value 3 -Force");

            // ═══ System Performance ═══
            sb.AppendLine("\n# --- System Performance ---");
            if (settings.Animations) { // Assume 'Animations' bool means 'Disable Animations' based on context in original view
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'UserPreferencesMask' -Value ([byte[]](0x90,0x12,0x03,0x80)) -Force");
            } else {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'UserPreferencesMask' -Value ([byte[]](0x9E,0x3E,0x07,0x80)) -Force"); // Default
            }

            if (settings.Transparency) {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' -Name 'EnableTransparency' -Value 0 -Force");
            } else {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' -Name 'EnableTransparency' -Value 1 -Force");
            }

            if (settings.BestPerformance) {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects' -Name 'VisualFXSetting' -Value 2 -Force");
            } else {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects' -Name 'VisualFXSetting' -Value 0 -Force"); // Let Windows choose
            }

            if (settings.BackgroundPriority) {
                sb.AppendLine("Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl' -Name 'Win32PrioritySeparation' -Value 24 -Force"); // Background services
            } else {
                sb.AppendLine("Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl' -Name 'Win32PrioritySeparation' -Value 2 -Force"); // Programs (Default)
            }

            // ═══ Storage ═══
            sb.AppendLine("\n# --- Storage ---");
            if (settings.DisableIndexing) {
                sb.AppendLine("Set-Service -Name WSearch -StartupType Disabled");
                sb.AppendLine("Stop-Service -Name WSearch -Force -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Set-Service -Name WSearch -StartupType Automatic");
            }

            if (settings.DisableDefrag) {
                sb.AppendLine("Disable-ScheduledTask -TaskPath '\\Microsoft\\Windows\\Defrag' -TaskName 'ScheduledDefrag' -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Enable-ScheduledTask -TaskPath '\\Microsoft\\Windows\\Defrag' -TaskName 'ScheduledDefrag' -ErrorAction SilentlyContinue");
            }

            // ═══ Startup & Services ═══
            sb.AppendLine("\n# --- Startup & Services ---");
            if (settings.DisableOneDrive) {
                sb.AppendLine("Get-Process -Name 'OneDrive' -ErrorAction SilentlyContinue | Stop-Process -Force");
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name 'OneDrive' -Value '' -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name 'OneDrive' -Value '\"C:\\Program Files\\Microsoft OneDrive\\OneDrive.exe\" /background' -ErrorAction SilentlyContinue");
            }

            if (settings.DisableCopilot) {
                sb.AppendLine("Set-ItemProperty -Path 'HKCU:\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot' -Name 'TurnOffWindowsCopilot' -Value 1 -Type DWord -Force -ErrorAction SilentlyContinue");
            } else {
                sb.AppendLine("Remove-ItemProperty -Path 'HKCU:\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot' -Name 'TurnOffWindowsCopilot' -Force -ErrorAction SilentlyContinue");
            }
            
            // ═══ Security ═══
            sb.AppendLine("\n# --- Security ---");
            if (settings.DisableRealTime) {
                sb.AppendLine("Set-MpPreference -DisableRealtimeMonitoring $true");
            } else {
                sb.AppendLine("Set-MpPreference -DisableRealtimeMonitoring $false");
            }

            if (settings.Firewall) {
                sb.AppendLine("Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True");
            } else {
                sb.AppendLine("Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False");
            }

            // ═══ Power & Sleep ═══
            sb.AppendLine("\n# --- Power & Sleep ---");
            if (settings.DisableSleep) {
                sb.AppendLine("powercfg /change standby-timeout-ac 0");
                sb.AppendLine("powercfg /change standby-timeout-dc 0");
            } else {
                sb.AppendLine("powercfg /change standby-timeout-ac 30");
            }

            if (settings.DisableHibernate) {
                sb.AppendLine("powercfg /h off");
            } else {
                sb.AppendLine("powercfg /h on");
            }

            // ═══ Recovery Watchdog ═══
            sb.AppendLine("\n# --- Recovery Watchdog ---");
            if (settings.DisableAutoRestart) {
                sb.AppendLine("Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\CrashControl' -Name 'AutoReboot' -Value 0 -Force");
            } else {
                sb.AppendLine("Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\CrashControl' -Name 'AutoReboot' -Value 1 -Force");
            }

            // ═══ Cleanup / Apply ═══
            sb.AppendLine("\n# --- Apply UI Changes ---");
            sb.AppendLine("Write-Host 'Restarting Explorer to apply UI changes...' -ForegroundColor Yellow");
            sb.AppendLine("Stop-Process -Name Explorer -Force");
            sb.AppendLine("Write-Host 'Deployment Complete!' -ForegroundColor Green");

            return sb.ToString();
        }
    }
}
